# Understanding Faiss

In [1]:
# #Install Packages
# !pip install faiss-cpu
# !pip install sentence-transformers

In [1]:
# import pandas 
import pandas as pd 

In [2]:
df = pd.read_csv("FAISS_text.csv")

In [3]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [4]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

In [5]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [6]:
vectors

array([[-0.00247392,  0.03626726, -0.05290463, ..., -0.09152359,
        -0.03970003, -0.04330489],
       [-0.03357269,  0.00980513, -0.03250129, ..., -0.05165462,
         0.02245887, -0.03156186],
       [-0.01865323, -0.04051303, -0.01235385, ...,  0.00610585,
        -0.07179644,  0.0277385 ],
       ...,
       [-0.00066465,  0.04252126, -0.05645507, ...,  0.01315469,
        -0.03183566, -0.04357661],
       [-0.03317156,  0.03252455, -0.02484838, ...,  0.01174424,
         0.05747128,  0.0057102 ],
       [-0.00166396,  0.00413831, -0.04597082, ...,  0.02008522,
         0.05656243, -0.00161596]], dtype=float32)

In [7]:
vectors.shape

(8, 768)

In [8]:
vectors[0]

array([-2.47391639e-03,  3.62672582e-02, -5.29046282e-02, -2.17348095e-02,
        1.41723175e-02, -1.01600774e-03,  2.23637465e-02,  3.65196578e-02,
        3.80902030e-02,  5.22008957e-03, -3.00866179e-02,  2.05440749e-03,
        1.08502805e-02, -8.49087164e-02, -5.57272788e-03, -6.06598295e-02,
        2.32015387e-03, -1.51409553e-02,  1.20671168e-02,  1.98904891e-02,
       -1.27936024e-02, -2.72811633e-02, -3.31878290e-02,  3.40647763e-03,
        8.41166638e-03, -1.94854848e-02,  4.88132350e-02,  2.24118400e-02,
        4.53466922e-02, -5.90891764e-02, -9.13182944e-02, -1.22327090e-03,
       -4.05045785e-02,  8.67182482e-03,  1.26565305e-06, -1.92451384e-02,
       -3.20659392e-02, -4.08172570e-02,  8.79177749e-02, -1.52632343e-02,
        1.09908953e-02, -4.47976738e-02, -4.74819820e-03,  3.52632105e-02,
        1.31070660e-02,  1.09944362e-02, -3.45768477e-03,  9.12349075e-02,
        5.68810217e-02,  4.82893400e-02, -4.51436825e-03,  3.58450636e-02,
       -2.44209673e-02, -

In [9]:
dim = vectors.shape[1]

In [10]:
dim

768

In [11]:
import faiss
index = faiss.IndexFlatL2(dim)

In [12]:
index


<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000002399095C570> >

In [13]:
index.add(vectors)

In [25]:
search_query = "Looking for places to visit  during holidays"

In [26]:
vec = encoder.encode(search_query)

In [27]:
vec.shape

(768,)

In [28]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [29]:
svec.shape

(1, 768)

In [30]:
index.search(svec, k=2)

(array([[0.83245456, 1.0380962 ]], dtype=float32),
 array([[6, 7]], dtype=int64))

In [31]:
dis, I = index.search(svec, k=2)

In [32]:
dis

array([[0.83245456, 1.0380962 ]], dtype=float32)

In [33]:
I

array([[6, 7]], dtype=int64)

In [34]:
df.loc[I[0]]

text category
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel